### ISSUE TITLE
Tracking Issue: Documentation

### ISSUE THREAD

**Issue by devzeroex** [devzeroex/grey#3]
This is a tracking-issue for _The SIG Docs_, the official documentation set for SIG.

Current status:

- [ ] _The Grey Spec_ (language spec)
- [ ] `grey`'s supported options, commands, etc.
- [ ] "What's New in 0.1.0" (overview of changes; not meant to be in-depth or a blow-by-blow; name is WiP)
- [ ] Tutorial (yes, it's early; no, IDGAF)
