### ISSUE TITLE
Tracking-Issue: _The Grey Spec_

### ISSUE THREAD

**Issue by devzeroex** [devzeroex/grey#4]
This is a tracking-issue for _The Grey Spec_, the specification for the Grey programming language.

- [x] Introduction
- [x] Explanation of the grammatical notation used
- [x] Define tokens
- [ ] Define all pre-runtime errors (in progress)
- [ ] Control flow
- [ ] Variable / constant definitions
- [ ] Struct definitions
- [ ] Interface definitions
- [ ] Function definitions
- [ ] Type system
- [ ] Module system
- [ ] Importing modules
- [ ] Accessibility / visibility system (public, protected, private)
- [ ] Define core library

More stuff may be added to the above list. See also #3 (_Tracking Issue: Documentation_).
